title: Study Blog
description: 学习随笔
google_analytics:
github:
    theme: https://github.com/pages-themes/leap-day
    me: https://github.com/quizhizhe/study-blog
theme: jekyll-theme-leap-day

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: default
      permalink: /posts/:title/